# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [1]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [2]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista)

Ejercicio 3: Suma los siguientes dos arrays

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [4]:
a + b

array([[11, 13, 15],
       [17, 19, 21]])

Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [5]:
a = np.array([[4,2,2],
              [4,1,0]])

In [6]:
a * 3.2

array([[12.8,  6.4,  6.4],
       [12.8,  3.2,  0. ]])

Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [8]:
a = np.array([x for x in range(9)])

print("Dimensión", a.shape)

a.reshape(3,3)
print("Dimensión", a.reshape(3,3).shape)

Dimensión (9,)
Dimensión (3, 3)


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [9]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [10]:
a.astype(int)

array([[2, 3, 1],
       [4, 2, 1]])

Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [11]:
np.eye(5).astype(bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [12]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [14]:
np.hstack((a1, a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Ejercicio 9: Cocatena de forma vertical los mismos array

In [15]:
np.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [17]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [18]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [19]:
np.where(a > b)

(array([2, 4]),)

Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [20]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [21]:
np.full((2, 3), 23)

array([[23, 23, 23],
       [23, 23, 23]])

Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [23]:
np.random.normal(0, 1, (8, 2))

array([[ 0.98903881, -0.93665822],
       [-1.59919087, -0.13122878],
       [ 1.65591901,  0.26120697],
       [ 1.12307432, -1.17190506],
       [ 0.28240546,  0.6056058 ],
       [-0.84155494, -0.20799891],
       [ 0.17065144,  0.5950556 ],
       [-0.10971409, -1.1251951 ]])

Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [24]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [ ]:
# Multiplicar como matrices
matrix_multiplication = np.dot(a, b)

# Multiplicar como arrays
elementwise_multiplication = a * b

matrix_multiplication, elementwise_multiplication

(array([[ 36,  42,  48],
        [ 81,  96, 111],
        [126, 150, 174]]),
 array([[ 2,  6, 12],
        [20, 30, 42],
        [56, 72, 90]]))

Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [28]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [33]:
# Ordenar de forma ascendente
ascending_order = np.sort(a)

# Ordenar de forma descendente
descending_order = np.sort(a)[::-1]

ascending_order, descending_order

(array([   0,    1,    2,    2,   38,   82,   91,  199,  292,  299,  387,
         923,  939, 1101]),
 array([1101,  939,  923,  387,  299,  292,  199,   91,   82,   38,    2,
           2,    1,    0]))

----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [35]:
import pandas as pd

In [50]:
df = pd.read_csv("datasets/venta_libros.csv", header=None)
df.head()

0  1    2
0  2019  1  106
1  2019  2  400
2  2019  3  339
3  2019  4  389
4  2019  5  141

In [51]:
year = np.array(df[0])
month = np.array(df[1])
books = np.array(df[2])

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [53]:
max_books = np.max(books)
max_books_index = np.argmax(books)
max_books_year = year[max_books_index]
max_books_month = month[max_books_index]

max_books, max_books_year, max_books_month

(489, 2021, 8)

Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [56]:
print('Suma: ', np.sum(books))
print('Media: ', np.mean(books))
print('Mediana: ', np.median(books))
print('Desviación estándar: ', np.std(books))

Suma:  12542
Media:  261.2916666666667
Mediana:  267.0
Desviación estándar:  136.60770450657444
